### ISSUE TITLE
docker-compose.yml' is invalid

### ISSUE THREAD

**Issue by BuiVanDuc** [absmach/magistrala#1388]
Hi everyone, when I run docker compose then it occur error like the below message:
`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.authn.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.authn.ports contains an invalid type, it should be a number, or an object
services.authn.ports contains an invalid type, it should be a number, or an object
services.http-adapter.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.things.ports contains an invalid type, it should be a number, or an object
services.things.ports contains an invalid type, it should be a number, or an object
services.things.ports contains an invalid type, it should be a number, or an object
services.users.ports contains an invalid type, it should be a number, or an object
services.coap-adapter.ports contains an invalid type, it should be a number, or an object
services.coap-adapter.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.nginx.ports value [':', ':', ':', ':'] has non-unique elements
services.things.ports value [':', ':', ':'] has non-unique elements
services.authn.ports value [':', ':'] has non-unique elements
services.jaeger.ports value [':/udp', ':', ':', ':'] has non-unique elements
`
How do I fix this issue?
thanks

**Comment by mteodor** [comment]
have you updated your branch?

**Comment by BuiVanDuc** [comment]
Hi @mteodor I'm using code on v0.11.0 bracnh

**Comment by mteodor** [comment]
in `docker-compose.yml`
add following change
instead of
`image: mainflux/auth:latest`
put
`image: mainflux/auth:0.11.0`
auth service is given as an example, yuo should do the same for all mainflux services

**Comment by BuiVanDuc** [comment]
I have changed image version in `docker-compose` file as you suggested but it still not work

**Comment by mteodor** [comment]
ah, sorry, you will have to build your own images 
first do cleanup
`make cleandocker`
than 
`make dockers`
and then start composition
of course given that you are on the 0.11.0 branch

additionally you have to start docker composition from the project directory as `docker-comopse` relies on `.env` file for reading environment variables

**Comment by manuio** [comment]
@BuiVanDuc Check the name of the services because they changed since `0.11.0`
Try with `mainflux/authn:l0.11.0`

**Comment by mteodor** [comment]
now I double checked, yes there are tags for `0.11.0` so replacement solution must work 
( I made a mistake and looked into `auth` service which is released after `0.11.0` and has only `latest`, `auth` service replaces `authn` )
additionally you have to start docker composition from the project directory as `docker-comopse` relies on `.env` file for reading environment variables

**Comment by hytan96** [comment]
I did a workaround and I able to run `make run` command.
The solution will be moving `.env` file from `./mainflux` to `./mainflux/docker` folder. Edit the `docker-compose.yml` in `./mainflux/docker/`, change the pathname in line 40 to `./.env`. Then you just have to redirect back to `./mainflux` and run the `make run` command. It seems like something didn't handle well at the backend, the workaround sounds insane but it really working after I try out this silly solution.

**Comment by BuiVanDuc** [comment]
@hytan96 I have tried to your mention but it's still not working

**Comment by mteodor** [comment]
I just tried to run `0.11.0` and it started correctly
Steps:
```
git clone https://github.com/mainflux/mainflux
cd mainflux
git checkout 0.11.0
```
edit the `docker-compose.yml`
```
docker-compose -f docker/docker-compose.yml up
ating volume "docker_mainflux-users-db-volume" with default driver
Creating volume "docker_mainflux-things-db-volume" with default driver
Creating volume "docker_mainflux-things-redis-volume" with default driver
Creating volume "docker_mainflux-es-redis-volume" with default driver
Creating volume "docker_mainflux-mqtt-broker-volume" with default driver
Pulling nats (nats:1.3.0)...
1.3.0: Pulling from library/nats
f3780679080c: Pull complete
5b0525adc546: Pull complete
Digest: sha256:f69bea91ead1a68870d16f775b27efd456a49b97cc140bc8a3f315bb5d0132cf
Status: Downloaded newer image for nats:1.3.0
Pulling authn-db (postgres:10.8-alpine)...
10.8-alpine: Pulling from library/postgres
e7c96db7181b: Pull complete
ddab92d60ba9: Pull complete
8c4b0e7b82b8: Pull complete
1241ee300dd7: Pull complete
8b19e293c1b6: Pull complete
f3fc4a6aefa8: Pull complete
b35e09974eb5: Pull complete
a1c8c0a60cc9: Pull complete
b53dfb9d9a64: Pull complete
Digest: sha256:3bb9237a58cdfbe3c720852675e5b37eca43ab96f79e261c648960c24a452e6d
Status: Downloaded newer image for postgres:10.8-alpine
Pulling authn (mainflux/authn:0.11.0)...
0.11.0: Pulling from mainflux/authn
d8b121e72bb6: Pull complete
fc7043c67840: Pull complete
Digest: sha256:18c375a906b78a1c7acbc627ac3ef787fd4f538cbbfb36cefa0b886d17b38dc9
Status: Downloaded newer image for mainflux/authn:0.11.0
Pulling users (mainflux/users:0.11.0)...
......
```

Content of the `docker-compose.yml`

```yaml
# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

version: "3.7"

networks:
  mainflux-base-net:
    driver: bridge

volumes:
  mainflux-authn-db-volume:
  mainflux-users-db-volume:
  mainflux-things-db-volume:
  mainflux-things-redis-volume:
  mainflux-es-redis-volume:
  mainflux-mqtt-broker-volume:

services:
  nginx:
    image: nginx:1.16.0-alpine
    container_name: mainflux-nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx-${AUTH-key}.conf:/etc/nginx/nginx.conf.template
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/snippets:/etc/nginx/snippets
      - ./ssl/authorization.js:/etc/nginx/authorization.js
      - ./ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
      - ./ssl/certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
      - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - ${MF_NGINX_HTTP_PORT}:${MF_NGINX_HTTP_PORT}
      - ${MF_NGINX_SSL_PORT}:${MF_NGINX_SSL_PORT}
      - ${MF_NGINX_MQTT_PORT}:${MF_NGINX_MQTT_PORT}
      - ${MF_NGINX_MQTTS_PORT}:${MF_NGINX_MQTTS_PORT}
    networks:
      - mainflux-base-net
    env_file:
      - ../.env
    command: /entrypoint.sh
    depends_on:
      - things
      - users
      - mqtt-adapter
      - http-adapter

  nats:
    image: nats:1.3.0
    container_name: mainflux-nats
    command: "-c /etc/nats/nats.conf"
    restart: on-failure
    volumes:
      - ./nats/:/etc/nats
    networks:
      - mainflux-base-net

  authn-db:
    image: postgres:10.8-alpine
    container_name: mainflux-authn-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${MF_AUTHN_DB_USER}
      POSTGRES_PASSWORD: ${MF_AUTHN_DB_PASS}
      POSTGRES_DB: ${MF_AUTHN_DB}
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-authn-db-volume:/var/lib/postgresql/data

  authn:
    image: mainflux/authn:0.11.0
    container_name: mainflux-authn
    depends_on:
      - authn-db
    expose:
      - ${MF_AUTHN_GRPC_PORT}
    restart: on-failure
    environment:
      MF_AUTHN_LOG_LEVEL: ${MF_AUTHN_LOG_LEVEL}
      MF_AUTHN_DB_HOST: authn-db
      MF_AUTHN_DB_PORT: ${MF_AUTHN_DB_PORT}
      MF_AUTHN_DB_USER: ${MF_AUTHN_DB_USER}
      MF_AUTHN_DB_PASS: ${MF_AUTHN_DB_PASS}
      MF_AUTHN_DB: ${MF_AUTHN_DB}
      MF_AUTHN_HTTP_PORT: ${MF_AUTHN_HTTP_PORT}
      MF_AUTHN_GRPC_PORT: ${MF_AUTHN_GRPC_PORT}
      MF_AUTHN_SECRET: ${MF_AUTHN_SECRET}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
    ports:
      - ${MF_AUTHN_HTTP_PORT}:${MF_AUTHN_HTTP_PORT}
      - ${MF_AUTHN_GRPC_PORT}:${MF_AUTHN_GRPC_PORT}
    networks:
      - mainflux-base-net

  users-db:
    image: postgres:10.8-alpine
    container_name: mainflux-users-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${MF_USERS_DB_USER}
      POSTGRES_PASSWORD: ${MF_USERS_DB_PASS}
      POSTGRES_DB: ${MF_USERS_DB}
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-users-db-volume:/var/lib/postgresql/data

  users:
    image: mainflux/users:0.11.0
    container_name: mainflux-users
    volumes:
      - ./users/emailer/templates/${MF_EMAIL_TEMPLATE}:/${MF_EMAIL_TEMPLATE}
    depends_on:
      - users-db
      - authn
    restart: on-failure
    environment:
      MF_USERS_LOG_LEVEL: ${MF_USERS_LOG_LEVEL}
      MF_USERS_DB_HOST: users-db
      MF_USERS_DB_PORT: ${MF_USERS_DB_PORT}
      MF_USERS_DB_USER: ${MF_USERS_DB_USER}
      MF_USERS_DB_PASS: ${MF_USERS_DB_PASS}
      MF_USERS_DB: ${MF_USERS_DB}
      MF_USERS_HTTP_PORT: ${MF_USERS_HTTP_PORT}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_EMAIL_DRIVER: ${MF_EMAIL_DRIVER}
      MF_EMAIL_HOST: ${MF_EMAIL_HOST}
      MF_EMAIL_PORT: ${MF_EMAIL_PORT}
      MF_EMAIL_USERNAME: ${MF_EMAIL_USERNAME}
      MF_EMAIL_PASSWORD: ${MF_EMAIL_PASSWORD}
      MF_EMAIL_FROM_ADDRESS: ${MF_EMAIL_FROM_ADDRESS}
      MF_EMAIL_FROM_NAME: ${MF_EMAIL_FROM_NAME}
      MF_EMAIL_TEMPLATE: ${MF_EMAIL_TEMPLATE}
      MF_TOKEN_RESET_ENDPOINT: ${MF_TOKEN_RESET_ENDPOINT}
      MF_AUTHN_GRPC_URL: ${MF_AUTHN_GRPC_URL}
      MF_AUTHN_GRPC_TIMEOUT: ${MF_AUTHN_GRPC_TIMEOUT}
    ports:
      - ${MF_USERS_HTTP_PORT}:${MF_USERS_HTTP_PORT}
    networks:
      - mainflux-base-net

  things-db:
    image: postgres:10.8-alpine
    container_name: mainflux-things-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${MF_THINGS_DB_USER}
      POSTGRES_PASSWORD: ${MF_THINGS_DB_PASS}
      POSTGRES_DB: ${MF_THINGS_DB}
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-things-db-volume:/var/lib/postgresql/data

  things-redis:
    image: redis:5.0-alpine
    container_name: mainflux-things-redis
    restart: on-failure
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-things-redis-volume:/data

  things:
    image: mainflux/things:0.11.0
    container_name: mainflux-things
    depends_on:
      - things-db
      - authn
    restart: on-failure
    environment:
      MF_THINGS_LOG_LEVEL: ${MF_THINGS_LOG_LEVEL}
      MF_THINGS_DB_HOST: things-db
      MF_THINGS_DB_PORT: ${MF_THINGS_DB_PORT}
      MF_THINGS_DB_USER: ${MF_THINGS_DB_USER}
      MF_THINGS_DB_PASS: ${MF_THINGS_DB_PASS}
      MF_THINGS_DB: ${MF_THINGS_DB}
      MF_THINGS_CACHE_URL: things-redis:${MF_REDIS_TCP_PORT}
      MF_THINGS_ES_URL: es-redis:${MF_REDIS_TCP_PORT}
      MF_THINGS_HTTP_PORT: ${MF_THINGS_HTTP_PORT}
      MF_THINGS_AUTH_HTTP_PORT: ${MF_THINGS_AUTH_HTTP_PORT}
      MF_THINGS_AUTH_GRPC_PORT: ${MF_THINGS_AUTH_GRPC_PORT}
      MF_THINGS_SECRET: ${MF_THINGS_SECRET}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_AUTHN_GRPC_URL: ${MF_AUTHN_GRPC_URL}
      MF_AUTHN_GRPC_TIMEOUT: ${MF_AUTHN_GRPC_TIMEOUT}
    ports:
      - ${MF_THINGS_HTTP_PORT}:${MF_THINGS_HTTP_PORT}
      - ${MF_THINGS_AUTH_HTTP_PORT}:${MF_THINGS_AUTH_HTTP_PORT}
      - ${MF_THINGS_AUTH_GRPC_PORT}:${MF_THINGS_AUTH_GRPC_PORT}
    networks:
      - mainflux-base-net

  jaeger:
    image: jaegertracing/all-in-one:1.13
    container_name: mainflux-jaeger
    ports:
      - ${MF_JAEGER_PORT}:${MF_JAEGER_PORT}/udp
      - ${MF_JAEGER_FRONTEND}:${MF_JAEGER_FRONTEND}
      - ${MF_JAEGER_COLLECTOR}:${MF_JAEGER_COLLECTOR}
      - ${MF_JAEGER_CONFIGS}:${MF_JAEGER_CONFIGS}
    networks:
      - mainflux-base-net

  vernemq:
    image: mainflux/vernemq:0.11.0
    container_name: mainflux-vernemq
    restart: on-failure
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: ${MF_DOCKER_VERNEMQ_ALLOW_ANONYMOUS}
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: ${MF_DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL}
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-mqtt-broker-volume:/var/lib/vernemq

  mqtt-adapter:
    image: mainflux/mqtt:0.11.0
    container_name: mainflux-mqtt
    depends_on:
      - vernemq
      - things
      - nats
    restart: on-failure
    environment:
      MF_MQTT_ADAPTER_LOG_LEVEL: ${MF_MQTT_ADAPTER_LOG_LEVEL}
      MF_MQTT_ADAPTER_MQTT_PORT: ${MF_MQTT_ADAPTER_MQTT_PORT}
      MF_MQTT_ADAPTER_WS_PORT: ${MF_MQTT_ADAPTER_WS_PORT}
      MF_MQTT_ADAPTER_ES_URL: es-redis:${MF_REDIS_TCP_PORT}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_MQTT_ADAPTER_MQTT_TARGET_HOST: vernemq
      MF_MQTT_ADAPTER_MQTT_TARGET_PORT: ${MF_MQTT_BROKER_PORT}
      MF_MQTT_ADAPTER_WS_TARGET_HOST: vernemq
      MF_MQTT_ADAPTER_WS_TARGET_PORT: ${MF_MQTT_BROKER_WS_PORT}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_THINGS_AUTH_GRPC_URL: ${MF_THINGS_AUTH_GRPC_URL}
      MF_THINGS_AUTH_GRPC_TIMEOUT: ${MF_THINGS_AUTH_GRPC_TIMEOUT}
    networks:
      - mainflux-base-net

  http-adapter:
    image: mainflux/http:0.11.0
    container_name: mainflux-http
    depends_on:
      - things
      - nats
    restart: on-failure
    environment:
      MF_HTTP_ADAPTER_LOG_LEVEL: debug
      MF_HTTP_ADAPTER_PORT: ${MF_HTTP_ADAPTER_PORT}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_THINGS_AUTH_GRPC_URL: ${MF_THINGS_AUTH_GRPC_URL}
      MF_THINGS_AUTH_GRPC_TIMEOUT: ${MF_THINGS_AUTH_GRPC_TIMEOUT}
    ports:
      - ${MF_HTTP_ADAPTER_PORT}:${MF_HTTP_ADAPTER_PORT}
    networks:
      - mainflux-base-net

  es-redis:
    image: redis:5.0-alpine
    container_name: mainflux-es-redis
    restart: on-failure
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-es-redis-volume:/data

  coap-adapter:
    image: mainflux/coap:0.11.0
    container_name: mainflux-coap
    depends_on:
      - things
      - nats
    restart: on-failure
    environment:
      MF_COAP_ADAPTER_LOG_LEVEL: ${MF_COAP_ADAPTER_LOG_LEVEL}
      MF_COAP_ADAPTER_PORT: ${MF_COAP_ADAPTER_PORT}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_THINGS_AUTH_GRPC_URL: ${MF_THINGS_AUTH_GRPC_URL}
      MF_THINGS_AUTH_GRPC_TIMEOUT: ${MF_THINGS_AUTH_GRPC_TIMEOUT}
    ports:
      - ${MF_COAP_ADAPTER_PORT}:${MF_COAP_ADAPTER_PORT}/udp
      - ${MF_COAP_ADAPTER_PORT}:${MF_COAP_ADAPTER_PORT}/tcp
    networks:
      - mainflux-base-net

```
I'm running on Ubuntu 20.04
docker-compose version 1.24.1, build 4667896b
