### ISSUE TITLE
Add example configuration about adding persistent storage for the things-db and users-db containers

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#636]
Hi,

We had a small discussion with @bergernetch on our Gitter channel about adding persistent storage to the `things-db` and `users-db` and he sent me updated docker-compose configs with added volumes for these contaners plus influxdb and grafana (the influxdb writer).
The changes are practically addition of top level `volumes` definitions and usage of these volumes in the container definitions. The volumes are mapped to the default location host machine, something like `/var/lib/docker/volumes/project-name_volume-name`.

The relevant sections are:
[main docker-compose.yml](https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml)
```
volumes:
  mainflux-users-db-volume:
  mainflux-things-db-volume:
...
  users-db:
    image: postgres:10.2-alpine
    container_name: mainflux-users-db
    restart: on-failure
    environment:
      POSTGRES_USER: mainflux
      POSTGRES_PASSWORD: mainflux
      POSTGRES_DB: users
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-users-db-volume:/var/lib/postgresql/data
...
  things-db:
    image: postgres:10.2-alpine
    container_name: mainflux-things-db
    restart: on-failure
    environment:
      POSTGRES_USER: mainflux
      POSTGRES_PASSWORD: mainflux
      POSTGRES_DB: things
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-things-db-volume:/var/lib/postgresql/data
```

and [influxdb-writer docker-compose.yml](https://github.com/mainflux/mainflux/blob/master/docker/addons/influxdb-writer/docker-compose.yml):
```
volumes:
  grafana-volume:
  influxdb-volume:
...
  influxdb:
    image: influxdb:1.6.4-alpine
    container_name: mainflux-influxdb
    restart: on-failure
    environment:
      INFLUXDB_DB: mainflux
      INFLUXDB_ADMIN_USER: mainflux
      INFLUXDB_ADMIN_PASSWORD: mainflux
    networks:
      - docker_mainflux-base-net
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
...
  grafana:
    image: grafana/grafana:5.1.3
    container_name: mainflux-grafana
    depends_on:
      - influxdb
    restart: on-failure
    ports:
      - 3001:3000
    networks:
      - docker_mainflux-base-net
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - PUID=0
      - GUID=0
```

I know that the definitions of external storage/volumes depend on the deployment strategy and can not be defined by us, but I find it useful if we have an example how one can configure a persistent storage for the dev setup, because with every new release someone who's trying out Mainflux is not careful, he or she will lose his/hers data. We already have the warning about the data loss in our [dev guide](https://github.com/mainflux/mainflux/blame/master/docs/dev-guide.md#L68).

I was thinking to add these examples in the dev guide, for our docker setup, but then if someone's using Mainflux with Kubernetes might also find such example configuration useful. A while ago we've spoken with @drasko about some kind of operations guide, but I think that would be to much to start it for two examples.

@mainflux/contributors What do you think about the idea of having an example persistent volume configuration in the dev guide? We could also provide patch files for those who want to use the changes.

Best Regards,
Jovan
P.S. I've also attached the whole configuration files [mainflux-persistence.zip](https://github.com/mainflux/mainflux/files/2939033/mainflux-persistence.zip).

**Comment by beres** [comment]
Hi @chombium 
Alternatively you can simply create a file named docker-compose.override.yml in the same folder of docker-compose.yml with for example 
`
version: "3"
services:
    users-db:
    volumes:
      - ../your/persistent/path/user_db:/var/lib/postgresql/data
`
When you execute docker-compose it is automatically evaluated.
You could also have docker-compose.my-special-name.yml with different values, in this case you have to specify the files when execute docker-compose
`docker-compose -f docker-compose.yml -f docker-compose.my-special-name.yml command ...`

Same approach can be used for other customization, for example
`  
version: "3"
services:
    nats:
        command: --debug -DV
`

Could be useful add to .gitignore docker-compose.*.yml :P

**Comment by beres** [comment]
...the two examples was
```
version: "3"

services:
  users-db:
    volumes:
      - ../your/persistent/path/user_db:/var/lib/postgresql/data
```

and

```
version: "3"

services:
  nats:
    command: --debug -DV
```
